---
- hosts: all
  sudo: yes

  handlers:
#    - include: handlers.yml

  pre_tasks:
#    - include: pre-tasks.yml

  roles:
#    - yfix.mc
#    - yfix.mysql

  tasks:
#    - include: tasks-apt.yml
#    - include: tasks-other.yml
#    - include: tasks-nginx.yml
#    - include: tasks-php-fpm.yml
    - include: tasks-mysql.yml
#    - include: tasks-memcached.yml
    - include: tasks-yf-framework.yml
    - include: handlers.yml

  post_tasks:
#    - include: post-tasks.yml
