---
    # nginx
    - apt_repository: repo='ppa:nginx/stable'
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600
    - apt: "name={{ item }} state=installed"
      with_items:
        - geoip-bin
        - geoip-database
        - nginx-extras
    - file: path=/etc/nginx/{{ item }} state=absent
      with_items:
        - fastcgi_params
        - koi-utf
        - koi-win
        - win-utf
        - scgi_params
        - uwsgi_params
        - conf.d
        - snippets
    - template: src=templates/nginx/{{ item }}.j2 dest=/etc/nginx/{{ item }} owner=root group=root mode=0644
      with_items:
        - basic.conf
        - fastcgi.conf
        - mime.types
        - nginx.conf
        - proxy_params
        - shared.conf
        - ssl.conf
        - sites-available/default
      notify: restart nginx
    - file: src=/etc/nginx/sites-available/default dest=/etc/nginx/sites-enabled/default state=link
    - file: path=/var/log/nginx state=directory owner=root group=root mode=0644
    - name: Ensure nginx is started and enabled to start at boot.
      service: name=nginx state=started enabled=yes
      notify: restart nginx
